### ISSUE TITLE
Fix broken dependabot's PRs

### ISSUE THREAD

**Issue by vmarkovtsev** [FragileTech/ml-ops-quickstart#195]
https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425

**Comment by vmarkovtsev** [comment]
Manual: https://hugo.alliau.me/2021/05/04/migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets/#share-your-secrets-with-dependabot

**Comment by Guillemdb** [comment]
I'm refactoring the code towards version 0.1.0. After its merged I'll fix it :)

**Comment by vmarkovtsev** [comment]
This is complex to fix, requires some deep magic. Wait for me please 😉 This is just to remember myself.
