### ISSUE TITLE
pytest -n 2 with pytest-xdist plugin

### ISSUE THREAD

**Issue by vmarkovtsev** [FragileTech/ml-ops-quickstart#38]
To execute unit tests 2x faster in GHA.

**Comment by Guillemdb** [comment]
I've never done that before. Can you point me to some example?

**Comment by vmarkovtsev** [comment]
Add `-n 2` to pytest cmdline and add pytest-xdist to `requirements-test.txt` 😁

**Comment by vmarkovtsev** [comment]
You can party hard and replace `2` with some autodetected number of cpus. Either xdist allow this or `$(getconf _NPROCESSORS_ONLN)`

**Comment by Guillemdb** [comment]
According to `pytest-xdist` docs passing `-n auto` will automatically use all the cpus available. I'm adding that on my next PR.
