### ISSUE TITLE
Improve workflow setups

### ISSUE THREAD

**Issue by Guillemdb** [FragileTech/ml-ops-quickstart#56]
We need to improve the workflow generation templates so it's possible to add the different jobs programmatically so that:
- [ ] Proprietary projects can use a private PyPI registry and docker image registry.
- [ ] Offer an option to disable PyPI deploy and test jobs.
- [x] Disable docker test/publish jobs in projects with no docker container 
- [ ] Disable style check in projects with no lint tools.
- [ ] Offer the option to disable the bump-version job.

**Comment by vmarkovtsev** [comment]
I am afraid that we will simply explode from the combinatorial variety of options and will not be able to ensure quality. IMHO we should stay reasonably opinionated, e.g., always lint and test the code, no matter what.

**Comment by Guillemdb** [comment]
Agree. I prefer quality over quantity :smile: 

 Pypi jobs can be disabled by omitting the secrets, same as Docker deploy. Lint and tests should be on every single CI, so if someone disagrees they can just delete the corresponding lines in push.yml. (Bump version is also too nice to disable)

I wouldn't mind adding support for private Docker and Pypi registries as long as some enterprise offers us to sponsor the development of that features.
