### ISSUE TITLE
Add an option to disable docker containers in a project

### ISSUE THREAD

**Issue by Guillemdb** [FragileTech/ml-ops-quickstart#57]
Depends on https://github.com/FragileTech/ml-ops-quickstart/issues/56

- [x] offer an option to set up a new project without a docker container.
- [x] publish docker images to DockerHub / GitHub Container Registry

**Comment by vmarkovtsev** [comment]
In progress.

**Comment by Guillemdb** [comment]
I'm really curious about how you are going to implement this 😋

**Comment by vmarkovtsev** [comment]
There are still tons of refactoring ahead. Let's see how quickly I'll merge #99

**Comment by vmarkovtsev** [comment]
We should test when docker is disabled.

**Comment by vmarkovtsev** [comment]
Heh. I tested and it did not work. Of course.

**Comment by vmarkovtsev** [comment]
Oh :D 
```python
project_config["docker"] = True  # use_docker
```

**Comment by vmarkovtsev** [comment]
https://github.com/FragileTech/ml-ops-quickstart/pull/109
